# Generated by Django 3.1.8 on 2021-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0002_auto_20210717_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsp',
            name='usages',
            field=models.FloatField(default=0),
        ),
    ]
