# Generated by Django 3.1.8 on 2021-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0003_dsp_usages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsp',
            name='usages',
            field=models.FloatField(),
        ),
    ]
