# Generated by Django 3.1.8 on 2021-07-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0004_auto_20210717_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsp',
            name='revenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dsp',
            name='usages',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
