# Generated by Django 3.1 on 2021-07-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0005_auto_20210717_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsr',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.currency'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='territory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.territory'),
        ),
    ]
