version: '3.7'

services:
  web:
    image: 127.0.0.1:5000/backend-software:latest
    build:
      context: ./backend-software
      dockerfile: Dockerfile
    command:  gunicorn digital.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend-software/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [ node.role == worker ]
      restart_policy:
        condition: on-failure

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

  nginx:
    image: 127.0.0.1:5000/nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - jenkins_data:/var/jenkins_home
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == worker ]
      restart_policy:
        condition: on-failure
volumes:
  postgres_data:
  portainer_data:
  jenkins_data:
  static_volume:
  media_volume:

